### ISSUE TITLE
Add clock and window parameters to totp

### ISSUE THREAD

**Issue by angelosarto** [tadeck/onetimepass#14]
Add in two features that exists in the [oath](http://www.nongnu.org/oath-toolkit/liboath-api/liboath-oath.html) library.  Specifically the ability to specify a specific clock time other than the current for generate and for validate.  And the ability to specify a window of time intervals on each side of the clock that will be considered to be successful in valid_totp.

**Comment by tadeck** [comment]
Implemented in #16.
