### ISSUE TITLE
wrong OTP size due to int number being used

### ISSUE THREAD

**Issue by maxadamo** [tadeck/onetimepass#17]
Hi. 
I have seen tokens shorter than others and I think it happens because you use 'int', hence when the first digit is a zero it is stripped. 
For instance, an attempt with a random secret, on that precise moment, gave me this result: 

`>>> my_secret='5keaubwr6am3xmoogkjqxt56t4puuu52'`
`>>> otp.get_totp(my_secret)`
`79770` 

p.s.: I didn't try to add a leading zero and login, as the secret was random, and I couldn't use this OTP in a real scenario.

**Comment by tadeck** [comment]
Hi, @maxadamo, you are right this is the default behavior, but this module already supports returning tokens with leading zeros.

Try the following (`as_string` keyword argument):

```python
>>> my_secret='5keaubwr6am3xmoogkjqxt56t4puuu52'
>>> otp.get_totp(my_secret, as_string=True)
'079770'
```

Please let me know if this solves your problem.

**Comment by maxadamo** [comment]
Hi. 
Of course it solves the issue and I am closing it. 
Thanks a lot for the prompt feedback!
